### ISSUE TITLE
NaN should throw TypeError instead of yield an empty range

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-Number.range#60]
_Originally posted by @ljharb in https://github.com/tc39/proposal-Number.range/pull/59#discussion_r1037762824_

**Comment by ljharb** [comment]
Specifically because it's definitely a bug, and it should fail early and loudly.

**Comment by bakkot** [comment]
See also https://github.com/tc39/proposal-iterator-helpers/issues/169 and https://github.com/tc39/proposal-temporal/issues/2112, where we agreed on rejecting NaN and things which coerce to NaN (unless they have some other meaning pre-coercion, of course).

In https://github.com/tc39/proposal-iterator-helpers/pull/181 we did decide on a RangeError rather than a TypeError, though.

**Comment by ljharb** [comment]
I agree a RangeError is more appropriate.
